# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build

permissions:
  contents: read
  pull-requests: write

on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: setup gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          add-job-summary-as-pr-comment: 'on-failure'
          allow-snapshot-wrappers: true
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build --scan

      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            build/libs/*.jar
            !build/libs/*-dev.jar
            !build/libs/*-sources.jar
            !build/libs/*-javadoc.jar
